<?php

namespace AppBundle\Repository;

/**
 * AftellijstRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AftellijstRepository extends \Doctrine\ORM\EntityRepository
{
}
